[project]
name = "do-github"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.9.2",
    "networkx>=3.4.2",
    "numpy>=2.1.2",
    "pyscipopt>=5.1.1",
]
